services:
  postgres:
    image: postgres:16-alpine
    container_name: template-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template_service
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - template-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: template-service-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - template-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  template-network:
    driver: bridge

